///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SISE
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidaPagoPoliza recording.
    /// </summary>
    [TestModule("ef805a31-cbb1-4c2b-b768-880d54f76493", ModuleType.Recording, 1)]
    public partial class ValidaPagoPoliza : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SISERepository repository.
        /// </summary>
        public static SISERepository repo = SISERepository.Instance;

        static ValidaPagoPoliza instance = new ValidaPagoPoliza();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidaPagoPoliza()
        {
            PolizaConvertida = "";
            NroPoliza = "04104008212";
            Remesa = "3083669";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidaPagoPoliza Instance
        {
            get { return instance; }
        }

#region Variables

        string _PolizaConvertida;

        /// <summary>
        /// Gets or sets the value of variable PolizaConvertida.
        /// </summary>
        [TestVariable("f212a9d8-12ac-4fcd-ac8e-b8e46e580347")]
        public string PolizaConvertida
        {
            get { return _PolizaConvertida; }
            set { _PolizaConvertida = value; }
        }

        string _NroPoliza;

        /// <summary>
        /// Gets or sets the value of variable NroPoliza.
        /// </summary>
        [TestVariable("5d7a7bea-c37e-4e38-9b78-a1b6f2a0e0cd")]
        public string NroPoliza
        {
            get { return _NroPoliza; }
            set { _NroPoliza = value; }
        }

        string _Remesa;

        /// <summary>
        /// Gets or sets the value of variable Remesa.
        /// </summary>
        [TestVariable("8ff7176c-b4a7-4f09-8488-e4d5fed898fc")]
        public string Remesa
        {
            get { return _Remesa; }
            set { _Remesa = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            PolizaConverter();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", PolizaConvertida, new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'sistema{Return}' with focus on 'SisePreProd'.", repo.SisePreProd.SelfInfo, new RecordItemIndex(3));
            repo.SisePreProd.Self.PressKeys("sistema{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(4));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '990{Return}' with focus on 'SisePreProd'.", repo.SisePreProd.SelfInfo, new RecordItemIndex(5));
            repo.SisePreProd.Self.PressKeys("990{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(6));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Sura2035{Return}' with focus on 'SisePreProd'.", repo.SisePreProd.SelfInfo, new RecordItemIndex(7));
            repo.SisePreProd.Self.PressKeys("Sura2035{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(8));
            Delay.Duration(2000, false);
            
            // Validación del Login (Texto: MENU PRINICPAL)
            ValidarLogin("M E N U    P R I N C I P A L", "Validación del Login");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1{Return}' with focus on 'SisePreProd'.", repo.SisePreProd.SelfInfo, new RecordItemIndex(10));
            repo.SisePreProd.Self.PressKeys("1{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(11));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1{Return}' with focus on 'SisePreProd'.", repo.SisePreProd.SelfInfo, new RecordItemIndex(12));
            repo.SisePreProd.Self.PressKeys("1{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(13));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1{Return}' with focus on 'SisePreProd'.", repo.SisePreProd.SelfInfo, new RecordItemIndex(14));
            repo.SisePreProd.Self.PressKeys("1{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(15));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2{Return}' with focus on 'SisePreProd'.", repo.SisePreProd.SelfInfo, new RecordItemIndex(16));
            repo.SisePreProd.Self.PressKeys("2{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(17));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NroPoliza' with focus on 'SisePreProd'.", repo.SisePreProd.SelfInfo, new RecordItemIndex(18));
            repo.SisePreProd.Self.PressKeys(NroPoliza);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SisePreProd'.", repo.SisePreProd.SelfInfo, new RecordItemIndex(19));
            repo.SisePreProd.Self.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(20));
            Delay.Duration(2000, false);
            
            // Validación de Pago
            ValidarLogin(Remesa, "Validación de Pago");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SisePreProd.Self, false, new RecordItemIndex(22));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SisePreProd.Sistema' at 18;6.", repo.SisePreProd.SistemaInfo, new RecordItemIndex(23));
            //repo.SisePreProd.Sistema.Click("18;6");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Putty.CopyAllToClipboard' at 122;9.", repo.Putty.CopyAllToClipboardInfo, new RecordItemIndex(24));
            //repo.Putty.CopyAllToClipboard.Click("122;9");
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
